### PR TITLE
[PW_SID:614152] [BlueZ,v2] fix build with glibc < 2.25

### PR DESCRIPTION
**Pull request by tedd-an**
getrandom and sys/random.h are only available since glibc 2.25:
https://www.gnu.org/software/gnulib/manual/html_node/sys_002frandom_002eh.html
resulting in the following build failures since version 5.63 and
https://git.kernel.org/pub/scm/bluetooth/bluez.git/log/?qt=grep&q=getrandom:

plugins/autopair.c:20:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^

To fix this build failure, add a getrandom fallback borrowed from
pipewire and licensed under MIT:
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/pipewire/utils.c

Fixes:
 - http://autobuild.buildroot.org/results/6b8870d12e0804d6154230a7322c49416c1dc0e2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
---
Changes v1 -> v2 (after review of Marcel Holtmann):
 - Add a getrandom fallback in src/missing.h instead of adding ifdef

 Makefile.am            |  1 +
 configure.ac           |  4 +++-
 emulator/le.c          |  3 +++
 emulator/phy.c         |  3 +++
 peripheral/main.c      |  3 +++
 plugins/autopair.c     |  3 +++
 profiles/health/hdp.c  |  3 +++
 profiles/health/mcap.c |  3 +++
 src/missing.h          | 30 ++++++++++++++++++++++++++++++
 tools/btgatt-server.c  |  3 +++
 10 files changed, 55 insertions(+), 1 deletion(-)
 create mode 100644 src/missing.h

### CODE REVIEW

**Comment by tedd-an** [comment]
**CheckPatch**
Test ID: checkpatch
Desc: Run checkpatch.pl script with rule in .checkpatch.conf
Duration: 0.91 seconds
**Result: FAIL**


Output:
```
[BlueZ,v2] fix build with glibc < 2.25
WARNING:COMMIT_LOG_LONG_LINE: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#81: 
https://www.gnu.org/software/gnulib/manual/html_node/sys_002frandom_002eh.html

/github/workspace/src/12745735.patch total: 0 errors, 1 warnings, 161 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

/github/workspace/src/12745735.patch has style problems, please review.

NOTE: Ignored message types: COMMIT_MESSAGE COMPLEX_MACRO CONST_STRUCT FILE_PATH_CHANGES MISSING_SIGN_OFF PREFER_PACKED SPDX_LICENSE_TAG SPLIT_STRING SSCANF_TO_KSTRTO

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

```

**Comment by tedd-an** [comment]
**GitLint**
Test ID: gitlint
Desc: Run gitlint with rule in .gitlint
Duration: 0.50 seconds
**Result: FAIL**


Output:
```
[BlueZ,v2] fix build with glibc < 2.25
14: B1 Line exceeds max length (83>80): "https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/pipewire/utils.c"
17: B1 Line exceeds max length (82>80): " - http://autobuild.buildroot.org/results/6b8870d12e0804d6154230a7322c49416c1dc0e2"

```

**Comment by tedd-an** [comment]
**Build - Prep**
Test ID: buildprep
Desc: Prepare environment for build
Duration: 0.36 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Configure**
Test ID: build
Desc: Configure the BlueZ source tree
Duration: 9.43 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Make**
Test ID: buildmake
Desc: Build the BlueZ source tree
Duration: 1417.36 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Make Check w/Valgrind**
Test ID: makecheckvalgrind
Desc: Run 'make check' with Valgrind
Duration: 510.92 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Make Distcheck**
Test ID: makedistcheck
Desc: Run distcheck to check the distribution
Duration: 265.04 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build w/ext ELL - Configure**
Test ID: build_extell
Desc: Configure BlueZ source with '--enable-external-ell' configuration
Duration: 9.51 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Incremental Build with patches**
Test ID: incremental_build
Desc: Incremental build per patch in the series
Duration: 0.00 seconds
**Result: PASS**
