### PR TITLE
[PW_SID:545463] profiles/audio/media.c: fix build with glibc >= 2.34


### PR DESCRIPTION
**Pull request by tedd-an**
pause() is defined in glibc since the very early times; it appears in
upstream commit 28f540f45bba (initial import) in 1995 [0].

Bluez has been defining a function named pause() for ages too, since
commit caab74c97542 (media: Implement new callbacks for pass-through
operations) in 2013 [1]

With the recent bump to glibc 2.34.xxx, the build now fails because the
two pause() clash:

profiles/audio/media.c:1284:13: error: conflicting types for 'pause'
1284 | static bool pause(void *user_data)
|             ^~~~~
In file included from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/bits/sigstksz.h:24,
from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/signal.h:328,
from /tmp/instance-0/output-1/per-package/bluez5_utils/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib/gbacktrace.h:36,
from /tmp/instance-0/output-1/per-package/bluez5_utils/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib.h:34,
from profiles/audio/media.c:21:
/tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/unistd.h:489:12: note: previous declaration of 'pause' was here
489 | extern int pause (void);
|            ^~~~~

The culprit is indeed glibc 2.34, as can be seen in this result matrix:

\   bluez5_utils
glibc \  5.60  |  5.61

### CODE REVIEW

**Comment by tedd-an** [comment]
**CheckPatch**
Test ID: checkpatch
Desc: Run checkpatch.pl script with rule in .checkpatch.conf
Duration: 0.39 seconds
**Result: FAIL**


Output:
```
profiles/audio/media.c: fix build with glibc >= 2.34
WARNING:UNKNOWN_COMMIT_ID: Unknown commit id '28f540f45bba', maybe rebased or not pulled?
#7: 
upstream commit 28f540f45bba (initial import) in 1995 [0].

WARNING:UNKNOWN_COMMIT_ID: Unknown commit id 'caab74c97542', maybe rebased or not pulled?
#10: 
commit caab74c97542 (media: Implement new callbacks for pass-through

WARNING:COMMIT_LOG_LONG_LINE: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#19: 
In file included from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/bits/sigstksz.h:24,

- total: 0 errors, 3 warnings, 16 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

"[PATCH] profiles/audio/media.c: fix build with glibc >= 2.34" has style problems, please review.

NOTE: Ignored message types: COMMIT_MESSAGE COMPLEX_MACRO CONST_STRUCT FILE_PATH_CHANGES MISSING_SIGN_OFF PREFER_PACKED SPDX_LICENSE_TAG SPLIT_STRING SSCANF_TO_KSTRTO

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

```

**Comment by tedd-an** [comment]
**CheckPatch_v2**
Test ID: checkpatch_v2
Desc: Run checkpatch.pl script with rule in .checkpatch.conf
Duration: 0.59 seconds
**Result: FAIL**


Output:
```
profiles/audio/media.c: fix build with glibc >= 2.34
WARNING:UNKNOWN_COMMIT_ID: Unknown commit id '28f540f45bba', maybe rebased or not pulled?
#89: 
upstream commit 28f540f45bba (initial import) in 1995 [0].

WARNING:UNKNOWN_COMMIT_ID: Unknown commit id 'caab74c97542', maybe rebased or not pulled?
#92: 
commit caab74c97542 (media: Implement new callbacks for pass-through

WARNING:COMMIT_LOG_LONG_LINE: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#101: 
In file included from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/bits/sigstksz.h:24,

/github/workspace/src/12487665.patch total: 0 errors, 3 warnings, 16 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

/github/workspace/src/12487665.patch has style problems, please review.

NOTE: Ignored message types: COMMIT_MESSAGE COMPLEX_MACRO CONST_STRUCT FILE_PATH_CHANGES MISSING_SIGN_OFF PREFER_PACKED SPDX_LICENSE_TAG SPLIT_STRING SSCANF_TO_KSTRTO

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

```

**Comment by tedd-an** [comment]
**GitLint**
Test ID: gitlint
Desc: Run gitlint with rule in .gitlint
Duration: 0.13 seconds
**Result: FAIL**


Output:
```
profiles/audio/media.c: fix build with glibc >= 2.34
16: B1 Line exceeds max length (142>80): "In file included from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/bits/sigstksz.h:24,"
17: B1 Line exceeds max length (136>80): "                 from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/signal.h:328,"
18: B1 Line exceeds max length (160>80): "                 from /tmp/instance-0/output-1/per-package/bluez5_utils/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib/gbacktrace.h:36,"
19: B1 Line exceeds max length (149>80): "                 from /tmp/instance-0/output-1/per-package/bluez5_utils/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib.h:34,"
21: B1 Line exceeds max length (164>80): "/tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/unistd.h:489:12: note: previous declaration of 'pause' was here"
44: B1 Line exceeds max length (83>80): "  - http://autobuild.buildroot.org/results/c4fbface34be8815838fd7201621d7a8fddd32c5"
45: B1 Line exceeds max length (83>80): "  - http://autobuild.buildroot.org/results/62b88740f19fbe4a1ad7959dc141d539eb88c1f8"
47: B1 Line exceeds max length (95>80): "[0] https://sourceware.org/git/?p=glibc.git;a=commit;h=28f540f45bbacd939bfd07f213bcad2bf730b1bf"
48: B1 Line exceeds max length (82>80): "[1] https://github.com/bluez/bluez/commit/caab74c97542a56b591f0b16b44ab6ba4b40f0f5"

```

**Comment by tedd-an** [comment]
**GitLint_v2**
Test ID: gitlint_v2
Desc: Run gitlint with rule in .gitlint
Duration: 0.30 seconds
**Result: FAIL**


Output:
```
profiles/audio/media.c: fix build with glibc >= 2.34
2: B4 Second line is not empty: "upstream commit 28f540f45bba (initial import) in 1995 [0]."
14: B1 Line exceeds max length (142>80): "In file included from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/bits/sigstksz.h:24,"
15: B1 Line exceeds max length (136>80): "                 from /tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/signal.h:328,"
16: B1 Line exceeds max length (160>80): "                 from /tmp/instance-0/output-1/per-package/bluez5_utils/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib/gbacktrace.h:36,"
17: B1 Line exceeds max length (149>80): "                 from /tmp/instance-0/output-1/per-package/bluez5_utils/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/glib-2.0/glib.h:34,"
19: B1 Line exceeds max length (164>80): "/tmp/instance-0/output-1/per-package/bluez5_utils/host/s390x-buildroot-linux-gnu/sysroot/usr/include/unistd.h:489:12: note: previous declaration of 'pause' was here"
42: B1 Line exceeds max length (83>80): "  - http://autobuild.buildroot.org/results/c4fbface34be8815838fd7201621d7a8fddd32c5"
43: B1 Line exceeds max length (83>80): "  - http://autobuild.buildroot.org/results/62b88740f19fbe4a1ad7959dc141d539eb88c1f8"
45: B1 Line exceeds max length (95>80): "[0] https://sourceware.org/git/?p=glibc.git;a=commit;h=28f540f45bbacd939bfd07f213bcad2bf730b1bf"
46: B1 Line exceeds max length (82>80): "[1] https://github.com/bluez/bluez/commit/caab74c97542a56b591f0b16b44ab6ba4b40f0f5"

```

**Comment by tedd-an** [comment]
**Prep - Setup ELL**
Test ID: setupell
Desc: Clone, build, and install ELL
Duration: 47.62 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Prep**
Test ID: buildprep
Desc: Prepare environment for build
Duration: 0.17 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Configure**
Test ID: build
Desc: Configure the BlueZ source tree
Duration: 8.08 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Make**
Test ID: buildmake
Desc: Build the BlueZ source tree
Duration: 202.14 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Make Check**
Test ID: makecheck
Desc: Run 'make check'
Duration: 8.76 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Make Distcheck**
Test ID: makedistcheck
Desc: Run distcheck to check the distribution
Duration: 239.18 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build w/ext ELL - Configure**
Test ID: build_extell
Desc: Configure BlueZ source with '--enable-external-ell' configuration
Duration: 8.32 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build w/ext ELL - Make**
Test ID: build_extell_make
Desc: Build BlueZ source with '--enable-external-ell' configuration
Duration: 191.91 seconds
**Result: PASS**
