### PR TITLE
[PW_SID:614113] [BlueZ] fix build with glibc < 2.25

### PR DESCRIPTION
**Pull request by tedd-an**
getrandom and sys/random.h are only available since glibc 2.25:
https://www.gnu.org/software/gnulib/manual/html_node/sys_002frandom_002eh.html
resulting in the following build failures since version 5.63 and
https://git.kernel.org/pub/scm/bluetooth/bluez.git/log/?qt=grep&q=getrandom
so put back rand() as a fallback:

plugins/autopair.c:20:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^

Fixes:
 - http://autobuild.buildroot.org/results/6b8870d12e0804d6154230a7322c49416c1dc0e2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
---
 configure.ac           |  2 ++
 emulator/le.c          |  7 +++++++
 emulator/phy.c         |  7 +++++++
 peripheral/main.c      | 10 ++++++++++
 plugins/autopair.c     |  6 ++++++
 profiles/health/hdp.c  | 11 +++++++++++
 profiles/health/mcap.c | 10 ++++++++++
 tools/btgatt-server.c  |  6 ++++++
 8 files changed, 59 insertions(+)

### CODE REVIEW

**Comment by tedd-an** [comment]
**CheckPatch**
Test ID: checkpatch
Desc: Run checkpatch.pl script with rule in .checkpatch.conf
Duration: 0.89 seconds
**Result: FAIL**


Output:
```
[BlueZ] fix build with glibc < 2.25
WARNING:COMMIT_LOG_LONG_LINE: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#81: 
https://www.gnu.org/software/gnulib/manual/html_node/sys_002frandom_002eh.html

ERROR:SPACING: space required before the open parenthesis '('
#276: FILE: profiles/health/hdp.c:1505:
+	for(i = 0; i < HDP_ECHO_LEN; i++)

/github/workspace/src/12745617.patch total: 1 errors, 1 warnings, 201 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

/github/workspace/src/12745617.patch has style problems, please review.

NOTE: Ignored message types: COMMIT_MESSAGE COMPLEX_MACRO CONST_STRUCT FILE_PATH_CHANGES MISSING_SIGN_OFF PREFER_PACKED SPDX_LICENSE_TAG SPLIT_STRING SSCANF_TO_KSTRTO

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

```

**Comment by tedd-an** [comment]
**Prep - Setup ELL**
Test ID: setupell
Desc: Clone, build, and install ELL
Duration: 43.80 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Prep**
Test ID: buildprep
Desc: Prepare environment for build
Duration: 0.31 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Configure**
Test ID: build
Desc: Configure the BlueZ source tree
Duration: 8.35 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build - Make**
Test ID: buildmake
Desc: Build the BlueZ source tree
Duration: 1438.85 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build w/ext ELL - Configure**
Test ID: build_extell
Desc: Configure BlueZ source with '--enable-external-ell' configuration
Duration: 8.40 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Build w/ext ELL - Make**
Test ID: build_extell_make
Desc: Build BlueZ source with '--enable-external-ell' configuration
Duration: 1407.23 seconds
**Result: PASS**

**Comment by tedd-an** [comment]
**Incremental Build with patches**
Test ID: incremental_build
Desc: Incremental build per patch in the series
Duration: 0.00 seconds
**Result: PASS**
